---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: qlik/gradle
    tag: latest

inputs:
- name: easy-auth-server
- name: authserver-version

outputs:
- name: builds

run:
  path: easy-auth-server/ci/build.sh